[package]
name = "shell"
version = "0.1.0"
authors = ["Daniel Hammer <hammerapi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix="0.17.0"
addy="0.1.1"
pest="2.1.3"
pest_derive="2.1.0"
execute="0.2.6"
